export type Yokai = {
  slug: string;
  name: string;
  reading: string;
  classification: 'oni' | 'mononoke' | 'water' | 'mountain' | 'household' | 'animal' | 'modern' | 'global';
  region: string[];
  era: 'ancient' | 'medieval' | 'edo' | 'modern' | 'contemporary';
  appearance: string;
  legend: string;
  sources: string[];
  related?: string[];
};

const Y = (data: Yokai): Yokai => data;

export const YOKAI_LIST: Yokai[] = [
  Y({
    slug: 'kappa',
    name: '河童',
    reading: 'かっぱ',
    classification: 'water',
    region: ['全国', '九州', '東北'],
    era: 'ancient',
    appearance: '頭頂部に「皿」と呼ばれる凹みがあり、緑色の体色、亀の甲羅のような背中、水かきのある手足。背丈は子供程度とされる。',
    legend: '河童は水辺に棲むとされる日本最古級の妖怪のひとつ。地域により呼称が異なり、ガラッパ（九州）、メドチ（東北）、エンコウ（四国）など100以上の呼び名がある。水難事故の擬人化として民俗学者により論じられてきた一面と、稲作と結びついた水神の眷属としての一面を持つ。きゅうりを好み、相撲を取りたがる、人を引き込むなどの伝承が広く知られる。',
    sources: ['柳田國男『遠野物語』', '水木しげる『日本妖怪大全』'],
    related: ['kawauso', 'jakotsubabaa'],
  }),
  Y({
    slug: 'zashiki-warashi',
    name: '座敷童',
    reading: 'ざしきわらし',
    classification: 'household',
    region: ['東北', '岩手'],
    era: 'edo',
    appearance: '5-6歳ほどの子供の姿。赤い着物や髪を結った姿で語られることが多い。',
    legend: '主に岩手県を中心とする東北地方で語り継がれる家屋の精霊。座敷童が住む家は栄え、出て行くと家が傾くという伝承が知られる。二戸市金田一温泉の旅館は座敷童伝承で広く知られる。柳田國男『遠野物語』にも多くの座敷童譚が収録されている。',
    sources: ['柳田國男『遠野物語』第17話', '宮沢賢治の作品'],
    related: ['oshira-sama'],
  }),
  Y({
    slug: 'tengu',
    name: '天狗',
    reading: 'てんぐ',
    classification: 'mountain',
    region: ['全国', '関東', '近畿'],
    era: 'medieval',
    appearance: '赤い顔、長い鼻、山伏の装束、団扇を持ち、翼を備えて飛ぶ姿で描かれる。鼻が低い「カラス天狗」もある。',
    legend: '山岳信仰・修験道と深く結びついた山の妖怪。日本各地の霊山に住むとされ、京都・鞍馬山、神奈川・大山、東京・高尾山、群馬・迦葉山などが代表的な天狗の棲家として知られる。神通力を持ち、人を惑わせる一方、修験者を導く存在ともされた。江戸期には天狗道の信仰として独自の宗教観を形成した。',
    sources: ['『日本書紀』', '『今昔物語集』'],
    related: ['yamabushi', 'kamikakushi'],
  }),
  Y({
    slug: 'oni',
    name: '鬼',
    reading: 'おに',
    classification: 'oni',
    region: ['全国'],
    era: 'ancient',
    appearance: '角を持ち、虎の皮の腰布、金棒を手にした大男の姿が一般的。赤鬼・青鬼が代表的だが、女性の鬼（般若など）の伝承もある。',
    legend: '日本の妖怪を代表する存在で、地獄の獄卒・山中の怪異・疫病神など多様な姿で登場する。節分の豆まき、桃太郎の鬼退治、酒呑童子伝説、安達ヶ原の鬼婆など、日本文化に深く根付いている。仏教の地獄思想と山岳信仰、土着の死霊観念が習合して形成された概念。',
    sources: ['『今昔物語集』', '『酒呑童子』', '『大江山絵詞』'],
    related: ['hannya', 'jashin'],
  }),
  Y({
    slug: 'yuki-onna',
    name: '雪女',
    reading: 'ゆきおんな',
    classification: 'mountain',
    region: ['東北', '北陸', '北海道'],
    era: 'medieval',
    appearance: '白い着物を纏った美しい女性の姿。長い黒髪、肌は雪のように白く、足音を立てずに現れるとされる。',
    legend: '豪雪地帯で語られる雪の精霊。吹雪の夜に現れ、人を凍えさせる、または恋に落とすとされる。ラフカディオ・ハーン『怪談』に収録された雪女譚が、英語圏でも広く知られる契機となった。地域により呼称が異なり、雪降り婆、雪坊主、雪入道などのバリエーションがある。',
    sources: ['ラフカディオ・ハーン『怪談』', '宗祇『雪国紀行』'],
    related: ['yamababa'],
  }),
  Y({
    slug: 'rokurokubi',
    name: 'ろくろ首',
    reading: 'ろくろくび',
    classification: 'mononoke',
    region: ['全国'],
    era: 'edo',
    appearance: '一見普通の人間の姿だが、夜になると首が長く伸びる女性として描かれる。中には首が完全に体から離れて飛び回る「抜け首」もある。',
    legend: '江戸期の妖怪画に頻繁に登場する代表的な妖怪。鳥山石燕『画図百鬼夜行』など多くの妖怪図鑑に描かれた。怪奇譚というより、見世物・娯楽コンテンツとして庶民に親しまれた性格を持つ。心の歪みが首を伸ばすという因果譚として語られることもある。',
    sources: ['鳥山石燕『画図百鬼夜行』', '『絵本百物語』'],
    related: ['nukekubi'],
  }),
  Y({
    slug: 'kitsune',
    name: '狐',
    reading: 'きつね',
    classification: 'animal',
    region: ['全国'],
    era: 'ancient',
    appearance: '野生の狐の姿。年を経るごとに尾が増え、九尾の狐が最高位とされる。人に化ける際は美しい女性の姿を取ることが多い。',
    legend: '日本の動物信仰で最も重要な存在の一つ。稲荷神の眷属として神聖視される一方、「人を化かす」「狐火を起こす」「狐憑きとなる」など多面的な姿を持つ。京都・伏見稲荷大社を総本宮とする稲荷信仰は全国約3万社の神社を持ち、現代まで継承されている。',
    sources: ['『今昔物語集』', '上田秋成『雨月物語』'],
    related: ['tanuki', 'inari-shin'],
  }),
  Y({
    slug: 'tanuki',
    name: '狸',
    reading: 'たぬき',
    classification: 'animal',
    region: ['全国', '四国'],
    era: 'medieval',
    appearance: '野生の狸の姿。化ける際は人間の姿や物体（やかん、徳利など）に変身するとされる。',
    legend: '狐と並んで日本の動物信仰の代表格。狐が「術」を使うのに対し、狸は「腹鼓」「化け学」のような滑稽な要素が強調される傾向がある。四国（特に阿波・讃岐）には独自の狸文化があり、阿波の大狸伝説や金長狸などが知られる。佐渡・団三郎狸、淡路・芝右衛門狸も有名。',
    sources: ['『今昔物語集』', '『分福茶釜』'],
    related: ['kitsune', 'mujina'],
  }),
  Y({
    slug: 'umibozu',
    name: '海坊主',
    reading: 'うみぼうず',
    classification: 'water',
    region: ['全国', '太平洋沿岸'],
    era: 'edo',
    appearance: '巨大な黒い坊主頭の姿で海から現れる。目鼻立ちは不明瞭で、巨人ほどの大きさとされる。',
    legend: '船乗りの間で語り継がれてきた海の怪異。突然海面から現れ、船を沈めようとする、または何かを問いかけてくるとされる。海難事故や暴風雨を擬人化したものという解釈がある。各地で「船幽霊」「海和尚」などの近縁の伝承がある。',
    sources: ['『東遊記』', '『絵本百物語』'],
    related: ['funa-yurei'],
  }),
  Y({
    slug: 'funa-yurei',
    name: '船幽霊',
    reading: 'ふなゆうれい',
    classification: 'water',
    region: ['全国', '瀬戸内海', '東日本'],
    era: 'edo',
    appearance: '海上に立つ霊たちが、柄杓を差し出して水を求めるとされる。',
    legend: '海上で出会うとされる船員たちの霊。柄杓を渡すと船に水を注がれて沈められるため、底を抜いた柄杓を渡すという伝承が広く知られる。海難事故の犠牲者の霊を背景とした民俗信仰として、太平洋・日本海・瀬戸内海など各地に分布する。',
    sources: ['『東遊記』', '小泉八雲『怪談』'],
    related: ['umibozu'],
  }),
  Y({
    slug: 'rokuro-kubi-old',
    name: '抜け首',
    reading: 'ぬけくび',
    classification: 'mononoke',
    region: ['全国'],
    era: 'edo',
    appearance: '夜間、頭部が体から離れて空中を漂う。ろくろ首と混同されることもあるが、別系統の伝承。',
    legend: 'ろくろ首と並んで江戸期の妖怪画で人気のあった怪異。中国の『搜神記』に源流があり、東南アジアの「ペナンガラン」など類似の伝承が広く分布する点で注目される。',
    sources: ['鳥山石燕『画図百鬼夜行』'],
    related: ['rokurokubi'],
  }),
  Y({
    slug: 'kuchisake-onna',
    name: '口裂け女',
    reading: 'くちさけおんな',
    classification: 'modern',
    region: ['全国'],
    era: 'contemporary',
    appearance: 'マスクで口元を隠した女性。マスクを外すと口が耳まで裂けている。「私、キレイ？」と問いかけるとされる。',
    legend: '1970年代末に全国の小中学生の間で爆発的に流通した現代都市伝説の代表。1979年の岐阜・愛知を発端に短期間で全国化し、警察が出動する事態にもなった。社会学者・民俗学者により、戦後核家族化と児童の通学路の長距離化に伴う集合的不安の表現として論じられてきた。',
    sources: ['常光徹『学校の怪談』', 'ヤン・ハロルド・ブルンヴァン研究'],
    related: ['teketeke', 'hassakusama'],
  }),
  Y({
    slug: 'teketeke',
    name: 'テケテケ',
    reading: 'てけてけ',
    classification: 'modern',
    region: ['全国', '北海道'],
    era: 'contemporary',
    appearance: '下半身がない女性の姿で、両肘を使って素早く移動する。「テケテケ」という移動音が名称の由来。',
    legend: '1980-90年代に学校の怪談として広まった現代妖怪。地方都市の駅・線路の伝承から始まり全国に流通した。「学校の七不思議」の文脈で語られることが多く、現代の口承文化の代表例として研究対象となっている。',
    sources: ['常光徹『学校の怪談』'],
    related: ['kuchisake-onna', 'hanako-san'],
  }),
  Y({
    slug: 'hanako-san',
    name: 'トイレの花子さん',
    reading: 'といれのはなこさん',
    classification: 'modern',
    region: ['全国'],
    era: 'contemporary',
    appearance: 'おかっぱ髪の少女の姿。学校のトイレの3番目の個室で「はなこさん、いますか」と呼ぶと現れるとされる。',
    legend: '戦後の学校都市伝説の代表的存在。1950年代から各地で類似の伝承が報告され、1980-90年代の「学校の怪談」ブームで全国に定着した。映画・アニメ化もされ、日本の都市伝説を象徴するキャラクターとなった。',
    sources: ['常光徹『学校の怪談』', '映画『学校の怪談』シリーズ'],
    related: ['teketeke', 'kuchisake-onna'],
  }),
  Y({
    slug: 'hassakusama',
    name: '八尺様',
    reading: 'はっしゃくさま',
    classification: 'modern',
    region: ['全国'],
    era: 'contemporary',
    appearance: '身長8尺（約240cm）の女性。白いワンピース、麦わら帽子を被った姿で描かれる。',
    legend: '2000年代後半に2ちゃんねるの「洒落怖（しゃれにならないほど怖い話）」スレッドから生まれた現代都市伝説。インターネット発の妖怪として、ネット文化が生み出した代表的な現代怪異として研究されている。',
    sources: ['2ちゃんねるオカルト板「洒落怖」'],
    related: ['kuchisake-onna', 'teketeke'],
  }),
  Y({
    slug: 'jorogumo',
    name: '絡新婦',
    reading: 'じょろうぐも',
    classification: 'mononoke',
    region: ['全国', '関東'],
    era: 'edo',
    appearance: '美しい女性の姿だが、本体は大きな蜘蛛。男性を誘惑して捕食するとされる。',
    legend: '江戸期の妖怪画で人気のあった大蜘蛛の化身。「絡新婦」と書いて「じょろうぐも」と読む。源頼光の土蜘蛛退治伝説に連なる蜘蛛系怪異の系譜の中に位置づけられる。',
    sources: ['鳥山石燕『画図百鬼夜行』'],
    related: ['tsuchigumo', 'yamababa'],
  }),
  Y({
    slug: 'tsuchigumo',
    name: '土蜘蛛',
    reading: 'つちぐも',
    classification: 'mononoke',
    region: ['全国', '近畿'],
    era: 'ancient',
    appearance: '巨大な蜘蛛、または巨大な顔と人の体を持つ妖怪として描かれる。',
    legend: '『日本書紀』にも記録される古い妖怪で、源頼光の四天王（碓井貞光・卜部季武・坂田金時・渡辺綱）による退治伝説で知られる。古代の朝廷に従わなかった集団を妖怪化したものという史学的解釈がある。',
    sources: ['『日本書紀』', '『土蜘蛛草紙』'],
    related: ['jorogumo', 'shuten-doji'],
  }),
  Y({
    slug: 'nopperabou',
    name: 'のっぺらぼう',
    reading: 'のっぺらぼう',
    classification: 'mononoke',
    region: ['全国'],
    era: 'edo',
    appearance: '人間の姿だが、顔に目・鼻・口がない、つるりとしたのっぺりとした顔をしている。',
    legend: '小泉八雲『怪談』の「むじな」で英語圏に紹介された江戸期の有名妖怪。狸や狐の変化と関連付けて語られることが多い。「振り返ると顔がない」「逃げ込んだ先の人物もまた顔がない」という入れ子の恐怖構造で知られる。',
    sources: ['小泉八雲『怪談』「むじな」', '『絵本百物語』'],
    related: ['mujina', 'tanuki'],
  }),
  Y({
    slug: 'yamababa',
    name: '山姥',
    reading: 'やまんば',
    classification: 'mountain',
    region: ['全国', '東北', '中部'],
    era: 'medieval',
    appearance: '老婆の姿で山中に住む。乱れた白髪、大きな口、長身。',
    legend: '山中で人を喰らうとされる女性の鬼として、全国の山間部で語り継がれてきた。能・狂言の「山姥」、説経節、民話「飯食わぬ女房」など、多様なメディアで描かれてきた。安達ヶ原の鬼婆伝説（福島県二本松）はその代表例。',
    sources: ['能「山姥」', '民話「飯食わぬ女房」'],
    related: ['oni', 'jashin', 'adachigahara'],
  }),
  Y({
    slug: 'rokuro-bi',
    name: '一つ目小僧',
    reading: 'ひとつめこぞう',
    classification: 'mononoke',
    region: ['全国', '関東'],
    era: 'edo',
    appearance: '目が一つしかない子供の姿。和尚さんの装束を着ていることが多い。',
    legend: '江戸期の妖怪画に登場する代表的な一つ目妖怪。柳田國男により、古代の片目の神（目一箇命など）の信仰が変容したものと論じられた。妖怪というより親しみのあるキャラクターとして庶民に受容された側面が強い。',
    sources: ['鳥山石燕『画図百鬼夜行』', '柳田國男『一つ目小僧その他』'],
    related: ['nopperabou'],
  }),
  // 海外
  Y({
    slug: 'banshee',
    name: 'バンシー',
    reading: 'ばんしー',
    classification: 'global',
    region: ['アイルランド', 'スコットランド'],
    era: 'medieval',
    appearance: '長い髪の女性の姿で、白または灰色の装束を纏う。地域により若い女性、または老婆として描かれる。',
    legend: 'アイルランド・スコットランドのケルト系民間伝承に登場する女性の精霊。特定の一族に憑き、その家族の誰かが死ぬ前に泣き叫ぶ声で予兆を告げるとされる。「Bean Sidhe（妖精の女）」が語源。アイルランド系移民により北米にも伝承が伝わった。',
    sources: ['アイルランド民俗誌'],
    related: ['leanan-sidhe'],
  }),
  Y({
    slug: 'vampire',
    name: '吸血鬼',
    reading: 'きゅうけつき',
    classification: 'global',
    region: ['東欧', 'バルカン半島'],
    era: 'medieval',
    appearance: '青白い肌、鋭い犬歯、黒いマント。鏡に映らない、十字架・ニンニク・聖水・日光に弱いとされる。',
    legend: 'バルカン半島・東欧のスラブ民間伝承に源流を持つ。18世紀の東欧で起きた集団パニックで西欧に広まり、ブラム・ストーカー『ドラキュラ』（1897）により世界的なキャラクターとなった。ルーマニア・ブラン城が観光名所となっているのは小説のイメージによる二次的な現象。',
    sources: ['ブラム・ストーカー『ドラキュラ』', 'バルカン民俗誌'],
    related: ['banshee'],
  }),
  Y({
    slug: 'la-llorona',
    name: 'ラ・ヨローナ',
    reading: 'らよろーな',
    classification: 'global',
    region: ['メキシコ', '中米'],
    era: 'medieval',
    appearance: '白い装束を纏った女性の姿。夜の川辺で泣き声を上げるとされる。',
    legend: 'スペイン語圏で広く知られる女性の幽霊伝承。「La Llorona」は「泣く女」の意味。メキシコを中心に中米全域、米国南西部のヒスパニック系コミュニティでも語り継がれてきた。映画化作品も多数ある。',
    sources: ['メキシコ民俗誌'],
    related: ['vampire'],
  }),
  Y({
    slug: 'jiangshi',
    name: 'キョンシー',
    reading: 'きょんしー',
    classification: 'global',
    region: ['中国', '台湾', '香港'],
    era: 'medieval',
    appearance: '清朝官服を着た硬直した死体。両腕を前に伸ばし、両足で跳躍移動するとされる。',
    legend: '中国の道教・民間信仰に起源を持つ屍鬼。1980年代の香港映画『霊幻道士』シリーズで世界的に知られるようになった。額に貼られた呪符でその動きを止められるという描写が広く認知されている。',
    sources: ['中国民俗誌', '香港映画『霊幻道士』'],
    related: ['vampire'],
  }),
  Y({
    slug: 'pontianak',
    name: 'ポンティアナック',
    reading: 'ぽんてぃあなっく',
    classification: 'global',
    region: ['マレーシア', 'インドネシア'],
    era: 'medieval',
    appearance: '長い黒髪、白い着衣の女性。出産時に亡くなった女性の霊とされる。',
    legend: 'マレー語圏（マレーシア・インドネシア・シンガポール・ブルネイ）で広く語り継がれる女性の霊。フランジパニ（プルメリア）の香りを纏うとされ、複数のホラー映画の主役となっている。',
    sources: ['マレー民俗誌'],
    related: ['mae-nak'],
  }),
  Y({
    slug: 'mae-nak',
    name: 'メーナーク',
    reading: 'めーなーく',
    classification: 'global',
    region: ['タイ'],
    era: 'edo',
    appearance: '長い黒髪の女性、伝統的なタイ装束を纏う。',
    legend: 'タイで最も有名な民間伝承の一つ。プラカノン地区（バンコク）の女性メーナークの物語として、ラーマ4世時代から語り継がれてきた。映画化・舞台化が多数あり、現代タイ文化を代表する怪談として知られる。バンコクのメーナーク・プラカノン廟は今も参拝者で賑わう。',
    sources: ['タイ民俗誌'],
    related: ['pontianak'],
  }),
  Y({
    slug: 'krasue',
    name: 'クラスー',
    reading: 'くらすー',
    classification: 'global',
    region: ['タイ', 'カンボジア', 'ラオス'],
    era: 'medieval',
    appearance: '美しい女性の頭部が、内臓を引きずったまま夜空を飛び回るとされる。',
    legend: '東南アジア大陸部で広く語り継がれる夜間飛行する女性の霊。タイ・カンボジア・ラオスで類似の伝承が分布し、地域により呼称が異なる（クラスー、アープ、ピロー）。',
    sources: ['東南アジア民俗誌'],
    related: ['rokuro-kubi-old'],
  }),
  Y({
    slug: 'wendigo',
    name: 'ウェンディゴ',
    reading: 'うぇんでぃご',
    classification: 'global',
    region: ['北米', 'カナダ'],
    era: 'medieval',
    appearance: '痩せ細った巨人、灰色がかった皮膚、鹿のような角を持つ姿で描かれる。',
    legend: 'アルゴンキン語族系の北米先住民族の民俗伝承に登場する精霊。極寒の冬期、孤立した状況で人を狂気に追い込み、人肉食に走らせる存在とされる。現代ホラー文化（映画・小説）に大きな影響を与えた。',
    sources: ['北米先住民族民俗誌'],
    related: [],
  }),
  Y({
    slug: 'chupacabra',
    name: 'チュパカブラ',
    reading: 'ちゅぱかぶら',
    classification: 'global',
    region: ['中南米', '米国南部'],
    era: 'contemporary',
    appearance: '小型の獣類または爬虫類のような姿。背中に棘が並び、体長は1m前後とされる。',
    legend: '1990年代にプエルトリコで報告が始まった現代の未確認生物。家畜（特にヤギ）の血を吸うとされ、中南米から米国南部に報告が拡大した。現代の都市伝説・未確認動物学（クリプトゾオロジー）の代表例として広く知られる。',
    sources: ['現代の都市伝説'],
    related: ['vampire'],
  }),
  Y({
    slug: 'aswang',
    name: 'アスワング',
    reading: 'あすわんぐ',
    classification: 'global',
    region: ['フィリピン'],
    era: 'medieval',
    appearance: '昼は普通の人間、夜は犬・黒猫・大鳥・大蝙蝠などの動物に変身するとされる。',
    legend: 'フィリピンの民間信仰で最も恐れられる存在の一つ。スペイン植民地時代以前から伝わる土着信仰に由来し、複数のサブカテゴリ（ティクバラング、マナナンガル等）を持つ。フィリピンのホラー文化の中核を成す。',
    sources: ['フィリピン民俗誌'],
    related: ['pontianak'],
  }),
];

export const YOKAI_BY_SLUG = Object.fromEntries(
  YOKAI_LIST.map((y) => [y.slug, y]),
) as Record<string, Yokai>;

export const YOKAI_CLASSIFICATIONS: Array<{
  slug: Yokai['classification'];
  name: string;
  emoji: string;
  description: string;
}> = [
  { slug: 'oni', name: '鬼・地獄系', emoji: '👹', description: '日本の鬼、地獄の住人など' },
  { slug: 'mononoke', name: '物の怪', emoji: '🧪', description: 'ろくろ首、のっぺらぼう等' },
  { slug: 'water', name: '水辺・海の怪', emoji: '🌊', description: '河童、海坊主、船幽霊' },
  { slug: 'mountain', name: '山岳の怪', emoji: '⛰️', description: '天狗、山姥、雪女' },
  { slug: 'household', name: '家・屋敷の怪', emoji: '🏠', description: '座敷童など家屋の精霊' },
  { slug: 'animal', name: '動物系', emoji: '🦊', description: '狐、狸、貉など' },
  { slug: 'modern', name: '現代妖怪', emoji: '📺', description: '口裂け女、テケテケ、花子さん' },
  { slug: 'global', name: '海外の妖怪', emoji: '🌐', description: '世界各地の怪異伝承' },
];
